name: Deploy Jekyll to Cloudflare Workers

on:
  push:
    branches:
      - jekyll

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Install dependencies
        run: |
          gem install bundler
          bundle lock --add-platform x86_64-linux
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Install Workers dependencies
        working-directory: ./workers-site
        run: npm install

      - name: Authenticate with Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler whoami

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: wrangler deploy
